//! Inlay hints: the folds that clean and filter what the child offers.

use super::hover::source_type;
use super::*;

/// The text of a hint label, whether a string or parts.
pub(crate) fn hint_label(hint: &Value) -> String {
    match hint.get("label") {
        Some(Value::String(s)) => s.clone(),

        Some(Value::Array(parts)) => parts
            .iter()
            .filter_map(|p| p.get("value").and_then(Value::as_str))
            .collect(),

        _ => String::new(),
    }
}

/// The key a hint carries from the filter to the fold: the source
/// position of the name it types. The mapping runs between the two, and
/// it sends a generated byte to the head of the construct that wrote
/// it, which is a keyword.
pub(crate) const NAME_END: &str = "_alloyNameEnd";

/// Where a hint belongs when the emit wrote a `local` of its own for a
/// name the author gave.
///
/// `match e as n with` emits `local n = e`, `if local n = e` and
/// `while local n = e` emit `local n = _c1`, and `local { a, b } = t`
/// emits `local a, b = _1.a, _1.b`. The name is the author's and maps
/// back, so the hint stands one character past it; the byte the hint
/// sits on is generated, and the map sends that to the head of the
/// statement, which spells a keyword.
pub(crate) fn name_end(doc: &Doc, hint: &Value) -> Option<(u32, u32)> {
    // A parameter hint stands in front of its argument, not after a
    // name, so the byte before it says nothing about where it belongs.
    if !hint_label(hint).starts_with(':') {
        return None;
    }

    let (line, character) = hint.get("position").and_then(position_of_value)?;
    let at = offset_of(&doc.shadow, line, character)?;

    // The hint sits on generated text, right after a name that the
    // author wrote.
    if at == 0 || !doc.generated_offset(at) || doc.generated_offset(at - 1) {
        return None;
    }

    if !keywords::is_word_at(&doc.shadow, at - 1) {
        return None;
    }

    let (start, end) = keywords::word_range(&doc.shadow, at - 1);

    if end != at {
        return None;
    }

    let (line, character) = position_of(&doc.shadow, start);
    let (line, character) = doc.to_source(line, character);
    let source_at = offset_of(&doc.source, line, character)?;
    let (from, to) = keywords::word_range(&doc.source, source_at);

    // The map answers for the name itself, not for a construct that
    // holds it: the source spells the same word there.
    (from == source_at && doc.source.get(from..to) == doc.shadow.get(start..end))
        .then(|| position_of(&doc.source, to))
}

/// Moves a hint onto the name the author wrote, where the filter said
/// it belongs.
fn move_to_name_end(hint: &mut Value) {
    if let Some((line, character)) = hint.get(NAME_END).and_then(position_of_value) {
        hint["position"] = json!({ "line": line, "character": character });
    }
}

/// Whether a `local` or a `const` introduces the name that ends at a
/// position. Such a name takes a type annotation. A name a pattern
/// binds takes none, and neither does the alias of `match e as n with`.
fn takes_an_annotation(doc: &Doc, line: u32, character: u32) -> bool {
    let Some(text) = doc.source.lines().nth(line as usize) else {
        return false;
    };
    let before: String = text.chars().take(character as usize).collect();
    let head = before.trim_end_matches(|c: char| c.is_alphanumeric() || c == '_');

    matches!(head.split_whitespace().next_back(), Some("local" | "const"))
}

/// Writes a function's return type hint as `-> T` when the editor asks
/// for the arrow. Off, every hint keeps the colon.
///
/// Alloy spells a return type both ways, `function f(): T` and
/// `function f() -> T`, and a reader who writes the arrow wants the
/// hint to read like the file. Only the return hint takes it: a
/// variable and a parameter have one spelling, `local x: T` and
/// `f(a: T)`, so they keep the colon. The child stands a return hint
/// on the `)` that closes the parameters, which is what tells the
/// three apart.
///
/// The label reads `-> T` and the gutter spaces it with the hint's
/// padding. An edit carries no padding, so the edit writes ` -> T`:
/// accepting the hint leaves the space the language spells.
pub(crate) fn arrow_returns(hints: &mut [Value], doc: &Doc, on: bool) {
    if !on {
        return;
    }

    for h in hints.iter_mut() {
        let Some(rest) = hint_label(h).strip_prefix(':').map(str::to_string) else {
            continue;
        };
        let after_params = h
            .get("position")
            .and_then(position_of_value)
            .is_some_and(|(l, c)| closes_a_parameter_list(doc, l, c));

        if !after_params {
            continue;
        }

        let text = format!("->{rest}");
        h["label"] = json!(text);
        h["paddingLeft"] = json!(true);

        // The gutter takes its space from the padding, which no edit
        // carries. An accepted hint writes source, where the space in
        // front of the arrow is what the language spells, so the edit
        // holds one of its own.
        if h.pointer("/textEdits/0/newText").is_some() {
            h["textEdits"][0]["newText"] = json!(format!(" {text}"));
        }
    }
}

/// Whether a `)` stands right before a position: the parameter list of
/// a function, which its return type follows.
fn closes_a_parameter_list(doc: &Doc, line: u32, character: u32) -> bool {
    doc.source
        .lines()
        .nth(line as usize)
        .and_then(|text| text.chars().take(character as usize).last())
        == Some(')')
}

/// The hints as the source can hold them. A parameter hint that names
/// an emit slot goes. A type hint loses `@checked`, reads by the name
/// its line gives when the print is unwritable, inserts nothing when no
/// name is at hand, and stands on the name the filter found for it.
pub(crate) fn clean_hints(hints: &mut Vec<Value>, doc: &Doc) {
    hints.retain(|h| !emit_slot_hint(h));

    for h in hints.iter_mut() {
        move_to_name_end(h);
    }

    let parameters = declared_type_parameters(&doc.source);

    hints.retain_mut(|h| {
        // The label and the edit are one text.
        if let Some(text) = h
            .pointer("/textEdits/0/newText")
            .and_then(Value::as_str)
            .map(str::to_string)
            && hint_label(h).starts_with(':')
        {
            h["label"] = json!(text);
        }

        // A bound leaves the type parameter list at emit and joins every
        // use of the parameter as an intersection: the check artifact
        // casts `xs[i]` to `(T & Ord)`. The reader wrote `T`.
        if let Some(text) = drop_bound_intersections(&hint_label(h), doc) {
            h["label"] = json!(text.clone());

            if h.pointer("/textEdits/0/newText").is_some() {
                h["textEdits"][0]["newText"] = json!(text);
            }
        }

        let label = hint_label(h);

        if !label.starts_with(": ") {
            return true;
        }

        // `@checked` is an emit attribute; a written type carries none.
        let label = label
            .replace("@checked ", "")
            .replace("@native ", "")
            .replace("@checked", "");
        let annotation = label[2..].trim();
        let named = writable_type(annotation) && !undeclared_variable(annotation, &parameters);
        let position = h.get("position").and_then(position_of_value);
        // The child types a method's receiver from its body; the `impl`
        // says what it is.
        let on_self = position.is_some_and(|(l, c)| self_parameter(doc, l, c));
        let from_source = position.and_then(|(l, c)| source_type(doc, l, c));

        // `unknown` says nothing about the binding, and `~nil` is the
        // checker's own spelling for a negation Alloy never writes. An
        // empty gutter is quieter than a hint with no content.
        if matches!(annotation, "unknown" | "~nil") && from_source.is_none() {
            return false;
        }

        // A generic struct prints by the name of its metatable, which
        // carries no argument. The `new` on the line wrote them, so the
        // hint reads them back and its edit inserts a type that
        // compiles.
        let restores_arguments = |name: &str| {
            !annotation.contains('<')
                && name.contains('<')
                && name.split('<').next() == Some(annotation)
        };
        // `new Scheduler { phase = 3, data = nil }` prints as the record
        // it holds, `{ data: nil, phase: number }`. The body annotates
        // the binding, so the filter above keeps it, and it names none
        // of what the reader wrote. The struct on the line does.
        let prints_a_body = annotation.starts_with('{');
        let label = match (named && !on_self, from_source) {
            (true, Some(name)) if restores_arguments(&name) || prints_a_body => {
                format!(": {name}")
            }

            (true, _) => label,

            (false, Some(name)) => format!(": {name}"),

            (false, None) if named => label,

            // The print is a name the solver invented, `a` for an
            // untyped parameter or `add<a, b>` for what it returns. It
            // annotates nothing and it tells the reader nothing, so the
            // gutter stays empty.
            (false, None) if undeclared_variable(annotation, &parameters) => return false,

            (false, None) => {
                h.as_object_mut().map(|o| o.remove("textEdits"));
                truncate_hint(h, &label);

                return true;
            }
        };

        h["label"] = json!(label);

        // A generic struct prints without its arguments: Luau names a
        // metatable type and carries none. `: Slotted` would not
        // compile, so the hint reads and inserts nothing.
        if generic_struct(doc, label[2..].trim()) {
            h.as_object_mut().map(|o| o.remove("textEdits"));

            return true;
        }

        if truncate_hint(h, &label) {
            h.as_object_mut().map(|o| o.remove("textEdits"));

            return true;
        }

        if let Some(position) = h.get("position").cloned() {
            h["textEdits"] = json!([{
                "range": { "start": position.clone(), "end": position },
                "newText": label,
            }]);
        }

        true
    });

    // A hint the filter moved keeps its edit only where the syntax
    // takes an annotation. `if local n: T = e` takes one; the alias of
    // `match e as n with` and a name inside `local { a, b } = t` take
    // none, and an edit there writes text the parser rejects.
    for h in hints.iter_mut() {
        let moved = h.as_object_mut().and_then(|o| o.remove(NAME_END)).is_some();
        let fits = h
            .get("position")
            .and_then(position_of_value)
            .is_some_and(|(l, c)| takes_an_annotation(doc, l, c));

        if moved && !fits {
            h.as_object_mut().map(|o| o.remove("textEdits"));
        }
    }
}

/// Whether a printed type names a struct that takes type parameters
/// and gives it none. Luau prints a struct by its metatable's name, so
/// the arguments are gone, and `Slotted` or `Pair[]` names a type the
/// source cannot write. The name may sit anywhere in the text.
pub(crate) fn generic_struct(doc: &Doc, text: &str) -> bool {
    let generics = |name: &str| {
        std::iter::once(&doc.source)
            .chain(doc.import_sources.iter())
            .any(|src| src.contains(&format!("struct {name}<")))
    };
    let bytes = text.as_bytes();
    let mut at = 0;

    while at < bytes.len() {
        if !(bytes[at] as char).is_alphanumeric() && bytes[at] != b'_' {
            at += 1;

            continue;
        }

        let start = at;

        while at < bytes.len() && ((bytes[at] as char).is_alphanumeric() || bytes[at] == b'_') {
            at += 1;
        }

        let word = &text[start..at];

        if !text[at..].starts_with('<') && generics(word) {
            return true;
        }
    }

    false
}

/// A label too long for the gutter shows its head alone. True when the
/// label was cut, so what is left inserts nothing.
pub(crate) fn truncate_hint(h: &mut Value, label: &str) -> bool {
    if label.chars().count() <= 72 {
        return false;
    }

    let head: String = label.chars().take(69).collect();
    h["label"] = json!(format!("{}…", head.trim_end()));

    true
}

/// `_1:` and `_2:` are the payload slots of a tagged enum. The source
/// names neither, so neither belongs in the gutter.
pub(crate) fn emit_slot_hint(h: &Value) -> bool {
    let label = hint_label(h);
    let name = label.trim_end_matches(':');

    name.len() > 1 && name.starts_with('_') && name[1..].chars().all(|c| c.is_ascii_digit())
}

/// A type a source line can hold: no attribute, no solver clause, no
/// emit-only name, and nothing the child cut short.
pub(crate) fn writable_type(text: &str) -> bool {
    !text.contains('@')
        && !text.contains(" where ")
        && !text.contains('*')
        && !text.contains('…')
        && !text.contains("__")
        && !text.contains("CYCLE")
        // The child cuts a long table with `... N more ...`.
        && !text.contains(" more ...")
        // `_1` and `_2` are the payload slots of a tagged enum.
        && !text.contains("_1:")
        && !text.contains("_2:")
        // `~nil` negates a type; Alloy writes no negation. The checker's
        // own type functions, `intersect<T, ~nil>`, carry it.
        && !text.contains('~')
        && !text.contains("intersect<")
        && !text.contains("union<")
        // A type pack, `...any`, annotates no binding.
        && !text.starts_with("...")
        && !names_a_hidden_field(text)
}

/// Whether a type text names a field the emit made: `_head`, `_next`,
/// `_source`. A std type hides them, so a popup that prints them names
/// what the language does not document.
pub(crate) fn names_a_hidden_field(text: &str) -> bool {
    text.match_indices('_').any(|(i, _)| {
        let opens = text[..i]
            .chars()
            .next_back()
            .is_none_or(|c| matches!(c, '{' | ' ' | ',' | '('));
        let name: String = text[i..]
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();

        opens && text[i + name.len()..].starts_with(':')
    })
}

/// A solver variable the file never declares, `a` or `T`: no
/// annotation can name it. The whole type may be one, `T[]`, or a
/// member's may be, `{ read value: a }`.
pub(crate) fn undeclared_variable(text: &str, declared: &HashSet<String>) -> bool {
    let short = |name: &str| {
        name.len() <= 2
            && !name.is_empty()
            && name.chars().all(|c| c.is_ascii_alphanumeric())
            && name.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
            && !declared.contains(name)
    };

    if short(text.trim().trim_end_matches('?').trim_end_matches("[]")) {
        return true;
    }

    // Every word of the type: a short one the file never declared is a
    // solver variable wherever it stands. A word a `:` follows is a
    // member's key, and one a `<` follows takes arguments, so it names
    // a type of its own.
    let bytes = text.as_bytes();
    let mut at = 0;

    while at < bytes.len() {
        if !(bytes[at] as char).is_ascii_alphanumeric() && bytes[at] != b'_' {
            at += 1;

            continue;
        }

        let start = at;

        while at < bytes.len() && ((bytes[at] as char).is_ascii_alphanumeric() || bytes[at] == b'_')
        {
            at += 1;
        }

        let after = text[at..].trim_start();

        if short(&text[start..at]) && !after.starts_with('<') && !after.starts_with(':') {
            return true;
        }
    }

    false
}

/// Whether the hint sits right after the `self` parameter of a method.
pub(crate) fn self_parameter(doc: &Doc, line: u32, character: u32) -> bool {
    let Some(text) = doc.source.lines().nth(line as usize) else {
        return false;
    };
    let before: String = text.chars().take(character as usize).collect();

    text.contains("function ") && before.trim_end().ends_with("self")
}

/// A return type hint on an async function names the Future the caller
/// gets, with the emit's own module name off it: `: __alloy.Future<T>`
/// becomes `: Future<T>`.
///
/// The hint once read `: T`, because `async function f(): T` was the
/// only header the source took. Both headers are accepted now, and the
/// Future is the type the call site actually sees, so the hint names
/// that and its edit inserts a header that compiles.
pub(crate) fn name_future_hint(hint: &mut Value) {
    pub(crate) fn unwrap(text: &str) -> Option<String> {
        let rest = text.strip_prefix(": ")?;
        // `__alloy` is the emit's name for the std and belongs in no
        // hint a reader sees.
        let inner = rest.strip_prefix("__alloy.")?;

        match inner.starts_with("Future<") {
            true => Some(format!(": {inner}")),

            false => None,
        }
    }

    if let Some(new) = unwrap(&hint_label(hint)) {
        hint["label"] = json!(new);
    }

    if let Some(edits) = hint.get_mut("textEdits").and_then(Value::as_array_mut) {
        for edit in edits {
            if let Some(text) = edit.get("newText").and_then(Value::as_str)
                && let Some(new) = unwrap(text)
            {
                edit["newText"] = json!(new);
            }
        }
    }
}
