//! Inlay hints: the folds that clean and filter what the child offers.

use super::hover::source_type;
use super::*;

/// The text of a hint label, whether a string or parts.
pub(crate) fn hint_label(hint: &Value) -> String {
    match hint.get("label") {
        Some(Value::String(s)) => s.clone(),

        Some(Value::Array(parts)) => parts
            .iter()
            .filter_map(|p| p.get("value").and_then(Value::as_str))
            .collect(),

        _ => String::new(),
    }
}

/// The key a hint carries from the filter to the fold: the source
/// position of the name it types. The mapping runs between the two, and
/// it sends a generated byte to the head of the construct that wrote
/// it, which is a keyword.
pub(crate) const NAME_END: &str = "_alloyNameEnd";

/// Where a hint belongs when the emit wrote a `local` of its own for a
/// name the author gave.
///
/// `match e as n with` emits `local n = e`, `if local n = e` and
/// `while local n = e` emit `local n = _c1`, and `local { a, b } = t`
/// emits `local a, b = _1.a, _1.b`. The name is the author's and maps
/// back, so the hint stands one character past it; the byte the hint
/// sits on is generated, and the map sends that to the head of the
/// statement, which spells a keyword.
pub(crate) fn name_end(doc: &Doc, hint: &Value) -> Option<(u32, u32)> {
    // A parameter hint stands in front of its argument, not after a
    // name, so the byte before it says nothing about where it belongs.
    if !hint_label(hint).starts_with(':') {
        return None;
    }

    let (line, character) = hint.get("position").and_then(position_of_value)?;
    let at = offset_of(&doc.shadow, line, character)?;

    // The hint sits on generated text, right after a name that the
    // author wrote.
    if at == 0 || !doc.generated_offset(at) || doc.generated_offset(at - 1) {
        return None;
    }

    if !keywords::is_word_at(&doc.shadow, at - 1) {
        return None;
    }

    let (start, end) = keywords::word_range(&doc.shadow, at - 1);

    if end != at {
        return None;
    }

    let (line, character) = position_of(&doc.shadow, start);
    let (line, character) = doc.to_source(line, character);
    let source_at = offset_of(&doc.source, line, character)?;
    let (from, to) = keywords::word_range(&doc.source, source_at);

    // The map answers for the name itself, not for a construct that
    // holds it: the source spells the same word there.
    (from == source_at && doc.source.get(from..to) == doc.shadow.get(start..end))
        .then(|| position_of(&doc.source, to))
}

/// Moves a hint onto the name the author wrote, where the filter said
/// it belongs.
fn move_to_name_end(hint: &mut Value) {
    if let Some((line, character)) = hint.get(NAME_END).and_then(position_of_value) {
        hint["position"] = json!({ "line": line, "character": character });
    }
}

/// Whether a `local` or a `const` introduces the name that ends at a
/// position. Such a name takes a type annotation. A name a pattern
/// binds takes none, and neither does the alias of `match e as n with`.
fn takes_an_annotation(doc: &Doc, line: u32, character: u32) -> bool {
    let Some(text) = doc.source.lines().nth(line as usize) else {
        return false;
    };
    let before: String = text.chars().take(character as usize).collect();
    let head = before.trim_end_matches(|c: char| c.is_alphanumeric() || c == '_');

    matches!(head.split_whitespace().next_back(), Some("local" | "const"))
}

/// Writes a function's return type hint as `-> T` when the editor asks
/// for the arrow. Off, every hint keeps the colon.
///
/// Alloy spells a return type both ways, `function f(): T` and
/// `function f() -> T`, and a reader who writes the arrow wants the
/// hint to read like the file. Only the return hint takes it: a
/// variable and a parameter have one spelling, `local x: T` and
/// `f(a: T)`, so they keep the colon. The child stands a return hint
/// on the `)` that closes the parameters, which is what tells the
/// three apart.
///
/// The label reads `-> T` and the gutter spaces it with the hint's
/// padding. An edit carries no padding, so the edit writes ` -> T`:
/// accepting the hint leaves the space the language spells.
pub(crate) fn arrow_returns(hints: &mut [Value], doc: &Doc, on: bool) {
    if !on {
        return;
    }

    for h in hints.iter_mut() {
        let Some(rest) = hint_label(h).strip_prefix(':').map(str::to_string) else {
            continue;
        };
        let after_params = h
            .get("position")
            .and_then(position_of_value)
            .is_some_and(|(l, c)| closes_a_parameter_list(doc, l, c));

        if !after_params {
            continue;
        }

        let text = format!("->{rest}");
        h["label"] = json!(text);
        h["paddingLeft"] = json!(true);

        // The gutter takes its space from the padding, which no edit
        // carries. An accepted hint writes source, where the space in
        // front of the arrow is what the language spells, so the edit
        // holds one of its own.
        if h.pointer("/textEdits/0/newText").is_some() {
            h["textEdits"][0]["newText"] = json!(format!(" {text}"));
        }
    }
}

/// Whether a `)` stands right before a position: the parameter list of
/// a function, which its return type follows.
fn closes_a_parameter_list(doc: &Doc, line: u32, character: u32) -> bool {
    doc.source
        .lines()
        .nth(line as usize)
        .and_then(|text| text.chars().take(character as usize).last())
        == Some(')')
}

/// The hints as the source can hold them. A parameter hint that names
/// an emit slot goes. A type hint loses `@checked`, reads by the name
/// its line gives when the print is unwritable, inserts nothing when no
/// name is at hand, and stands on the name the filter found for it.
pub(crate) fn clean_hints(hints: &mut Vec<Value>, doc: &Doc) {
    hints.retain(|h| !emit_slot_hint(h));

    for h in hints.iter_mut() {
        move_to_name_end(h);
    }

    let parameters = declared_type_parameters(&doc.source);
    let modules = whole_modules(doc);
    let reach = super::completion::StdReach::of(doc);

    hints.retain_mut(|h| {
        // The label and the edit are one text.
        if let Some(text) = h
            .pointer("/textEdits/0/newText")
            .and_then(Value::as_str)
            .map(str::to_string)
            && hint_label(h).starts_with(':')
        {
            h["label"] = json!(text);
        }

        // A bound leaves the type parameter list at emit and joins every
        // use of the parameter as an intersection: the check artifact
        // casts `xs[i]` to `(T & Ord)`. The reader wrote `T`.
        if let Some(text) = drop_bound_intersections(&hint_label(h), doc) {
            h["label"] = json!(text.clone());

            if h.pointer("/textEdits/0/newText").is_some() {
                h["textEdits"][0]["newText"] = json!(text);
            }
        }

        // The child spells an `Iter` out as the table of its methods.
        let label = super::hover::fold_std_shapes(&hint_label(h));

        if !label.starts_with(": ") {
            return true;
        }

        // `@checked` is an emit attribute; a written type carries none.
        let label = label
            .replace("@checked ", "")
            .replace("@native ", "")
            .replace("@checked", "");
        let annotation = label[2..].trim();
        let named = writable_type(annotation) && !undeclared_variable(annotation, &parameters);
        let position = h.get("position").and_then(position_of_value);
        // The child types a method's receiver from its body; the `impl`
        // says what it is.
        let on_self = position.is_some_and(|(l, c)| self_parameter(doc, l, c));
        let from_source = position.and_then(|(l, c)| source_type(doc, l, c));

        // `unknown` says nothing about the binding, and neither does
        // `~nil`, the key the checker gives a loop over an untyped table.
        // An empty gutter is quieter than a hint with no content. A
        // narrower negation, `~number`, stays: the source can write it.
        if matches!(annotation, "unknown" | "~nil") && from_source.is_none() {
            return false;
        }

        // A generic struct prints by the name of its metatable, which
        // carries no argument. The `new` on the line wrote them, so the
        // hint reads them back and its edit inserts a type that
        // compiles.
        let restores_arguments = |name: &str| {
            !annotation.contains('<')
                && name.contains('<')
                && name.split('<').next() == Some(annotation)
        };
        // `new Scheduler { phase = 3, data = nil }` prints as the record
        // it holds, `{ data: nil, phase: number }`. The body annotates
        // the binding, so the filter above keeps it, and it names none
        // of what the reader wrote. The struct on the line does.
        let prints_a_body = annotation.starts_with('{');
        let label = match (named && !on_self, from_source) {
            (true, Some(name)) if restores_arguments(&name) || prints_a_body => {
                format!(": {name}")
            }

            (true, _) => label,

            (false, Some(name)) => format!(": {name}"),

            (false, None) if named => label,

            // The print is a name the solver invented, `a` for an
            // untyped parameter or `add<a, b>` for what it returns. It
            // annotates nothing and it tells the reader nothing, so the
            // gutter stays empty.
            (false, None) if undeclared_variable(annotation, &parameters) => return false,

            // The print spells out how the runtime lays out an enum or a
            // struct: `{ _1: "Junk" | { @metatable Item, ... } }`. The
            // hover names the type, and the layout names nothing the
            // source wrote, so the gutter stays empty.
            (false, None) if annotation.contains("@metatable") || annotation.contains("_1:") => {
                return false;
            }

            (false, None) => {
                h.as_object_mut().map(|o| o.remove("textEdits"));
                truncate_hint(h, &label);

                return true;
            }
        };

        let label = qualify_module_types(&label, &modules, doc);
        h["label"] = json!(label);

        // A generic struct or std collection prints without its
        // arguments: Luau names a metatable type and carries none.
        // `: HashMap` would not compile, so the hint reads and inserts
        // nothing.
        if generic_struct(doc, label[2..].trim()) {
            h.as_object_mut().map(|o| o.remove("textEdits"));

            return true;
        }

        if truncate_hint(h, &label) {
            h.as_object_mut().map(|o| o.remove("textEdits"));

            return true;
        }

        if let Some(position) = h.get("position").cloned() {
            // A std type the file does not reach comes with its import,
            // so the annotation the edit writes compiles.
            let missing = unreached_std_names(&label, &reach, doc);
            let fixes = alloy::std_names::import_fixes(&doc.source, &missing);
            let mut edits = vec![json!({
                "range": { "start": position.clone(), "end": position },
                "newText": label,
            })];
            edits.extend(super::completion::fix_edits(&doc.source, &fixes));
            h["textEdits"] = json!(edits);
        }

        true
    });

    // A hint the filter moved keeps its edit only where the syntax
    // takes an annotation. `if local n: T = e` takes one; the alias of
    // `match e as n with` and a name inside `local { a, b } = t` take
    // none, and an edit there writes text the parser rejects.
    for h in hints.iter_mut() {
        let moved = h.as_object_mut().and_then(|o| o.remove(NAME_END)).is_some();
        let fits = h
            .get("position")
            .and_then(position_of_value)
            .is_some_and(|(l, c)| takes_an_annotation(doc, l, c));

        if moved && !fits {
            h.as_object_mut().map(|o| o.remove("textEdits"));
        }
    }
}

/// The modules a file binds whole, each as its local and the types it
/// exports: `planck` for `import planck from "@pkg/planck"`. Only a
/// local the check artifact binds to the module itself counts,
/// `local planck = require(...)`; a default read through `.default`
/// holds no types.
fn whole_modules(doc: &Doc) -> Vec<(String, Vec<String>)> {
    use alloy_syntax::ast::{ImportKind, Stmt};

    if doc.import_types.is_empty() {
        return Vec::new();
    }

    let Ok(parsed) = alloy_syntax::parse_lenient(&doc.source, Default::default()) else {
        return Vec::new();
    };
    let toks = &parsed.lexed.toks;

    parsed
        .chunk
        .block
        .stmts
        .iter()
        .filter_map(|stmt| {
            let Stmt::Import(import) = stmt else {
                return None;
            };
            let name = match &import.kind {
                ImportKind::Default(n) | ImportKind::Both(n, _) | ImportKind::Namespace(n, _) => {
                    n.text(&doc.source, toks)
                }

                _ => return None,
            };
            let spec = import
                .path
                .text(&doc.source, toks)
                .trim_matches(['"', '\'']);
            let binds = format!("local {name} = require(");
            let whole = doc.shadow.lines().any(|line| {
                let line = line.trim().trim_end_matches(';');

                line.starts_with(&binds) && line.ends_with(')')
            });
            let (_, types) = doc.import_types.iter().find(|(s, _)| s == spec)?;

            whole.then(|| (name.to_string(), types.clone()))
        })
        .collect()
}

/// A printed type with each type another module exports written the way
/// the file reaches it. The checker prints `Scheduler<>` for the type
/// planck exports, and a bare `Scheduler` names nothing in a file that
/// imports planck whole; `planck.Scheduler<>` does. A name the file
/// declares or imports itself stays as it is.
pub(crate) fn qualify_module_types(
    text: &str,
    modules: &[(String, Vec<String>)],
    doc: &Doc,
) -> String {
    if modules.is_empty() {
        return text.to_string();
    }

    let bound = alloy::alx::bound_names(&doc.source);
    let is_word = |c: char| c.is_alphanumeric() || c == '_';
    let mut out = String::with_capacity(text.len());
    let mut at = 0;

    while let Some(c) = text[at..].chars().next() {
        if !is_word(c) {
            out.push(c);
            at += c.len_utf8();

            continue;
        }

        let end = text[at..]
            .find(|c: char| !is_word(c))
            .map_or(text.len(), |n| at + n);
        let word = &text[at..end];
        // `a.B` is a path already, and `key: T` names a field.
        let free = !text[..at].ends_with('.') && !text[end..].trim_start().starts_with(':');
        let own = bound.contains(word) || doc.decls.iter().any(|d| d.name == word);
        let module = modules
            .iter()
            .find(|(_, types)| types.iter().any(|t| alloy::modules::type_head(t) == word));

        if let Some((name, _)) = module.filter(|_| free && !own) {
            out.push_str(name);
            out.push('.');
        }

        out.push_str(word);
        at = end;
    }

    out
}

/// The std names a printed type holds that the file does not reach: no
/// import binds them, `[std] globals` keeps them out, and the file
/// declares none of its own by the name.
fn unreached_std_names<'a>(
    text: &'a str,
    reach: &super::completion::StdReach,
    doc: &Doc,
) -> Vec<&'a str> {
    let is_word = |c: char| c.is_alphanumeric() || c == '_';
    let mut out: Vec<&str> = Vec::new();
    let mut at = 0;

    while let Some(c) = text[at..].chars().next() {
        if !is_word(c) {
            at += c.len_utf8();

            continue;
        }

        let end = text[at..]
            .find(|c: char| !is_word(c))
            .map_or(text.len(), |n| at + n);
        let word = &text[at..end];
        // `a.B` is a path, and `key: T` names a field.
        let free = !text[..at].ends_with('.') && !text[end..].trim_start().starts_with(':');

        if free
            && alloy::std_names::is_std_name(word)
            && !reach.reaches(word)
            && !doc.decls.iter().any(|d| d.name == word)
            && !out.contains(&word)
        {
            out.push(word);
        }

        at = end;
    }

    out
}

/// Whether a printed type names a struct or a std type that takes type
/// parameters and gives it none. Luau prints a struct by its
/// metatable's name, so the arguments are gone, and `Slotted`, `Pair[]`
/// or `HashMap` names a type the source cannot write. The name may sit
/// anywhere in the text.
pub(crate) fn generic_struct(doc: &Doc, text: &str) -> bool {
    let generics = |name: &str| {
        std::iter::once(&doc.source)
            .chain(doc.import_sources.iter())
            .any(|src| src.contains(&format!("struct {name}<")))
            || (super::hover::std_generic(name) && !doc.decls.iter().any(|d| d.name == name))
    };
    let bytes = text.as_bytes();
    let mut at = 0;

    while at < bytes.len() {
        if !(bytes[at] as char).is_alphanumeric() && bytes[at] != b'_' {
            at += 1;

            continue;
        }

        let start = at;

        while at < bytes.len() && ((bytes[at] as char).is_alphanumeric() || bytes[at] == b'_') {
            at += 1;
        }

        let word = &text[start..at];

        if !text[at..].starts_with('<') && generics(word) {
            return true;
        }
    }

    false
}

/// A label too long for the gutter shows its head alone. True when the
/// label was cut, so what is left inserts nothing.
pub(crate) fn truncate_hint(h: &mut Value, label: &str) -> bool {
    if label.chars().count() <= 72 {
        return false;
    }

    let head: String = label.chars().take(69).collect();
    h["label"] = json!(format!("{}…", head.trim_end()));

    true
}

/// `_1:` and `_2:` are the payload slots of a tagged enum. The source
/// names neither, so neither belongs in the gutter.
pub(crate) fn emit_slot_hint(h: &Value) -> bool {
    let label = hint_label(h);
    let name = label.trim_end_matches(':');

    name.len() > 1 && name.starts_with('_') && name[1..].chars().all(|c| c.is_ascii_digit())
}

/// A type a source line can hold: no attribute, no solver clause, no
/// emit-only name, and nothing the child cut short.
pub(crate) fn writable_type(text: &str) -> bool {
    !text.contains('@')
        && !text.contains(" where ")
        && !text.contains('*')
        && !text.contains('…')
        && !text.contains("__")
        && !text.contains("CYCLE")
        // The child cuts a long table with `... N more ...`.
        && !text.contains(" more ...")
        // `_1` and `_2` are the payload slots of a tagged enum.
        && !text.contains("_1:")
        && !text.contains("_2:")
        // `~nil` is a type Alloy writes, but the checker's own type
        // functions, `intersect<T, ~nil>`, have no source form.
        && !text.contains("intersect<")
        && !text.contains("union<")
        // A type pack, `...any`, annotates no binding.
        && !text.starts_with("...")
        && !names_a_hidden_field(text)
}

/// Whether a type text names a field the emit made: `_head`, `_next`,
/// `_source`. A std type hides them, so a popup that prints them names
/// what the language does not document.
pub(crate) fn names_a_hidden_field(text: &str) -> bool {
    text.match_indices('_').any(|(i, _)| {
        let opens = text[..i]
            .chars()
            .next_back()
            .is_none_or(|c| matches!(c, '{' | ' ' | ',' | '('));
        let name: String = text[i..]
            .chars()
            .take_while(|c| c.is_alphanumeric() || *c == '_')
            .collect();

        opens && text[i + name.len()..].starts_with(':')
    })
}

/// A solver variable the file never declares, `a` or `T`: no
/// annotation can name it. The whole type may be one, `T[]`, or a
/// member's may be, `{ read value: a }`.
pub(crate) fn undeclared_variable(text: &str, declared: &HashSet<String>) -> bool {
    let short = |name: &str| {
        name.len() <= 2
            && !name.is_empty()
            && name.chars().all(|c| c.is_ascii_alphanumeric())
            && name.chars().next().is_some_and(|c| c.is_ascii_alphabetic())
            && !declared.contains(name)
    };

    if short(text.trim().trim_end_matches('?').trim_end_matches("[]")) {
        return true;
    }

    // Every word of the type: a short one the file never declared is a
    // solver variable wherever it stands. A word a `:` follows is a
    // member's key, and one a `<` follows takes arguments, so it names
    // a type of its own.
    let bytes = text.as_bytes();
    let mut at = 0;

    while at < bytes.len() {
        if !(bytes[at] as char).is_ascii_alphanumeric() && bytes[at] != b'_' {
            at += 1;

            continue;
        }

        let start = at;

        while at < bytes.len() && ((bytes[at] as char).is_ascii_alphanumeric() || bytes[at] == b'_')
        {
            at += 1;
        }

        let after = text[at..].trim_start();

        if short(&text[start..at]) && !after.starts_with('<') && !after.starts_with(':') {
            return true;
        }
    }

    false
}

/// Whether the hint sits right after the `self` parameter of a method.
pub(crate) fn self_parameter(doc: &Doc, line: u32, character: u32) -> bool {
    let Some(text) = doc.source.lines().nth(line as usize) else {
        return false;
    };
    let before: String = text.chars().take(character as usize).collect();

    text.contains("function ") && before.trim_end().ends_with("self")
}

/// A return type hint on an async function names the Future the caller
/// gets, with the emit's own module name off it: `: __alloy.Future<T>`
/// becomes `: Future<T>`.
///
/// The hint once read `: T`, because `async function f(): T` was the
/// only header the source took. Both headers are accepted now, and the
/// Future is the type the call site actually sees, so the hint names
/// that and its edit inserts a header that compiles.
pub(crate) fn name_future_hint(hint: &mut Value) {
    pub(crate) fn unwrap(text: &str) -> Option<String> {
        let rest = text.strip_prefix(": ")?;
        // `__alloy` is the emit's name for the std and belongs in no
        // hint a reader sees.
        let inner = rest.strip_prefix("__alloy.")?;

        match inner.starts_with("Future<") {
            true => Some(format!(": {inner}")),

            false => None,
        }
    }

    if let Some(new) = unwrap(&hint_label(hint)) {
        hint["label"] = json!(new);
    }

    if let Some(edits) = hint.get_mut("textEdits").and_then(Value::as_array_mut) {
        for edit in edits {
            if let Some(text) = edit.get("newText").and_then(Value::as_str)
                && let Some(new) = unwrap(text)
            {
                edit["newText"] = json!(new);
            }
        }
    }
}

/*
A binding of a module that exports only types and interfaces: the module
emits an empty table, so the checker's hint reads `{}`, which says
nothing and which a click would write as an annotation. The hint names
what the module carries instead, `{ type Id, interface Named }`, and an
interface reads as one, apart from the type aliases. It inserts nothing.

`import * as M from "spec"` and `local M = require("spec")` at the top of
a line bind a module. A hint the child sent for the same binding gives
way, including luau-lsp's own `{ type ... }` form, which cannot tell an
interface from a type.
*/
pub(crate) fn type_only_module_hints(hints: &mut Vec<Value>, doc: &Doc, path: &std::path::Path) {
    for (n, line) in doc.source.lines().enumerate() {
        let Some((name_end, spec)) = module_binding(line) else {
            continue;
        };
        let Some((target, exports)) = alloy::modules::type_only_exports(path, &spec) else {
            continue;
        };
        let (line_no, character) = (n as u32, line[..name_end].encode_utf16().count() as u32);

        hints.retain(|h| {
            h.get("position")
                .and_then(position_of_value)
                .is_none_or(|(l, c)| {
                    l != line_no || (c != character && !hint_label(h).starts_with(": { type "))
                })
        });

        hints.push(json!({
            "position": { "line": line_no, "character": character },
            "label": type_only_label(&path_to_uri(&target), &exports),
            "kind": 1,
        }));
    }
}

/// A hover on the name of a module binding whose module exports types
/// alone. The child prints the module's value, `{}`, and the types are
/// what the binding holds, as the hint lists them.
pub(crate) fn type_only_module_hover(
    text: &str,
    doc: &Doc,
    path: &std::path::Path,
    line: u32,
    character: u32,
) -> Option<String> {
    let source_line = doc.source.lines().nth(line as usize)?;
    let (name_end, spec) = module_binding(source_line)?;

    if character as usize > name_end || !text.contains(": {}") {
        return None;
    }

    let (_, exports) = alloy::modules::type_only_exports(path, &spec)?;
    let names: Vec<String> = exports
        .iter()
        .map(|e| match e.interface {
            true => format!("interface {}", e.name),

            false => format!("type {}", e.name),
        })
        .collect();

    Some(text.replacen(": {}", &format!(": {{ {} }}", names.join(", ")), 1))
}

/// `: { type Id, interface Named }` as label parts. Each name links to
/// its declaration, and the editor shows the hover there and follows the
/// definition found there. A tooltip would show the doc twice. The names
/// past the length every hint keeps are listed on the `...` part.
fn type_only_label(uri: &str, exports: &[alloy::modules::TypeExport]) -> Value {
    let mut parts = vec![json!({ "value": ": { " })];
    let mut length = 4;
    let mut hidden = String::new();

    for (i, e) in exports.iter().enumerate() {
        let entry = match e.interface {
            true => format!("interface {}", e.name),

            false => format!("type {}", e.name),
        };

        if !hidden.is_empty() || (i > 0 && length + entry.len() + 4 > 72) {
            hidden += &format!("\n- `{entry}`");

            continue;
        }

        if i > 0 {
            parts.push(json!({ "value": ", " }));
            length += 2;
        }

        length += entry.len();
        let (line, character) = e.at;
        let end = character + e.name.encode_utf16().count() as u32;
        parts.push(json!({
            "value": entry,
            "location": {
                "uri": uri,
                "range": {
                    "start": { "line": line, "character": character },
                    "end": { "line": line, "character": end },
                },
            },
        }));
    }

    if !hidden.is_empty() {
        parts.push(json!({
            "value": ", ...",
            "tooltip": { "kind": "markdown", "value": format!("Also exports:\n{hidden}") },
        }));
    }

    parts.push(json!({ "value": " }" }));

    Value::Array(parts)
}

/// The end of the name a line binds a module to, and the spec it
/// names: `import * as M from "spec"`, or `local M = require("spec")`
/// and its `const` form.
fn module_binding(line: &str) -> Option<(usize, String)> {
    let name_at = |rest: &str| {
        rest.find(|c: char| !(c.is_alphanumeric() || c == '_'))
            .unwrap_or(rest.len())
    };
    let quoted = |text: &str| {
        let q = text.chars().next().filter(|c| *c == '"' || *c == '\'')?;
        let body = &text[1..];

        body.find(q).map(|end| body[..end].to_string())
    };

    if let Some(rest) = line.strip_prefix("import * as ") {
        let len = name_at(rest);
        let spec = quoted(rest[len..].trim_start().strip_prefix("from")?.trim_start())?;

        return (len > 0).then(|| ("import * as ".len() + len, spec));
    }

    let keyword = ["local ", "const "]
        .into_iter()
        .find(|k| line.starts_with(k))?;
    let rest = &line[keyword.len()..];
    let len = name_at(rest);
    let call = rest[len..].trim_start().strip_prefix('=')?.trim_start();
    let spec = quoted(call.strip_prefix("require(")?)?;

    (len > 0).then(|| (keyword.len() + len, spec))
}

#[cfg(test)]
mod type_only_tests {
    #[test]
    fn a_module_binding_reads_its_name_and_spec() {
        let read = super::module_binding;

        assert_eq!(
            read("import * as Shapes from \"@shared/shapes\""),
            Some((18, "@shared/shapes".to_string()))
        );
        assert_eq!(
            read("local Raw = require('../shared/shapes')"),
            Some((9, "../shared/shapes".to_string()))
        );
        assert_eq!(
            read("const Raw = require(\"./x\")"),
            Some((9, "./x".to_string()))
        );
        assert_eq!(
            read("  local Raw = require(\"./x\")"),
            None,
            "top of a line only"
        );
        assert_eq!(read("import { Id } from \"./x\""), None);
        assert_eq!(read("local x = f(\"./x\")"), None);
    }

    /// The child prints a module of types alone as `{}`. The hover on
    /// the binding's name lists the types, as the hint does.
    #[test]
    fn a_type_only_module_hovers_as_its_types() {
        let dir = std::env::temp_dir().join(format!("alloy-type-only-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        std::fs::write(
            dir.join("types.aly"),
            "export type Id = string\n\nexport interface Named as\n  name: string\nend\n",
        )
        .expect("module");
        let src = "const T = require(\"./types\")\nprint(T)\n";
        let main = dir.join("main.aly");
        let doc = crate::doc::Doc::new(
            src.to_string(),
            1,
            &alloy::EmitOptions::default(),
            &alloy::luaux::Config::default(),
            None,
        );
        let hover = |character: u32| {
            super::type_only_module_hover("```alloy\nconst T: {}\n```", &doc, &main, 0, character)
        };

        assert_eq!(
            hover(6).as_deref(),
            Some("```alloy\nconst T: { type Id, interface Named }\n```")
        );
        // The spec is no part of the name.
        assert_eq!(hover(20), None);

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_type_only_label_documents_each_name_and_cuts_the_rest() {
        use alloy::modules::TypeExport;

        let export = |name: &str, interface: bool| TypeExport {
            name: name.to_string(),
            interface,
            at: (2, 12),
        };
        let label = super::type_only_label(
            "file:///a.aly",
            &[export("Id", false), export("Named", true)],
        );
        let parts = label.as_array().unwrap();

        assert_eq!(
            super::hint_label(&serde_json::json!({ "label": label })),
            ": { type Id, interface Named }"
        );
        assert_eq!(parts[1]["location"]["uri"], "file:///a.aly");
        assert_eq!(parts[1]["location"]["range"]["end"]["character"], 14);
        assert!(parts[1].get("tooltip").is_none());

        let long: Vec<TypeExport> = (0..12)
            .map(|i| export(&format!("LongTypeName{i}"), false))
            .collect();
        let label = super::type_only_label("file:///a.aly", &long);
        let text = super::hint_label(&serde_json::json!({ "label": label }));
        let parts = label.as_array().unwrap();
        let more = &parts[parts.len() - 2];

        assert!(text.chars().count() <= 72, "{text}");
        assert!(text.ends_with(", ... }"), "{text}");
        assert!(
            more["tooltip"]["value"]
                .as_str()
                .unwrap()
                .ends_with("\n- `type LongTypeName11`")
        );
    }
}
