/*!
The position map's contract, over the check artifact, which the map
follows. For every copied byte, forward then back is
the identity. For every output byte, back lands inside the source. Every
generated byte maps to an anchor on the same line as its output.
*/

use std::fs;
use std::path::Path;

fn line_of(text: &str, offset: usize) -> usize {
    text[..offset.min(text.len())].matches('\n').count()
}

/// A binder that declares its name on the anchor's line copies the
/// name from the source: the negated `if local`, a table pattern, an
/// array pattern. The editor then maps the child's answer back to the
/// name the reader wrote.
#[test]
fn a_binder_name_on_its_line_copies_from_the_source() {
    let src = concat!(
        "struct Pair as\n",
        "    a: number\n",
        "    b: number\n",
        "end\n",
        "local function first(): string?\n",
        "    return \"x\"\n",
        "end\n",
        "local function use_if_not_local(): string\n",
        "    if not local name = first() then\n",
        "        return \"none\"\n",
        "    end\n",
        "    return name\n",
        "end\n",
        "local function use_table_pattern(p: Pair): number\n",
        "    local { a, b } = p\n",
        "    return a + b\n",
        "end\n",
        "local function use_array_pattern(arr: number[]): number\n",
        "    local [first_item, ...rest] = arr\n",
        "    return first_item + #rest\n",
        "end\n",
    );
    let out = alloy::compile(src).unwrap();

    for (text, word) in [
        ("name = first()", "name"),
        ("a, b } = p", "a"),
        ("b } = p", "b"),
        ("first_item, ...rest", "first_item"),
        ("rest] = arr", "rest"),
    ] {
        let s = src.find(text).unwrap() as u32;
        let o = out
            .map
            .to_output(s)
            .unwrap_or_else(|| panic!("{word} is generated"));
        assert!(
            out.check[o as usize..].starts_with(word),
            "{word}: {}",
            &out.check[o as usize..]
        );
    }
}

#[test]
fn forward_then_back_is_identity_on_copied_bytes() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/cases");

    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();

        if path.extension().and_then(|e| e.to_str()) != Some("aly") {
            continue;
        }

        let src = fs::read_to_string(&path).unwrap();
        let out = alloy::compile(&src).unwrap();

        for s in 0..=src.len() as u32 {
            if let Some(o) = out.map.to_output(s) {
                assert_eq!(out.map.to_source(o), s, "{}: byte {s}", path.display());
                assert_eq!(
                    line_of(&src, s as usize),
                    line_of(&out.check, o as usize),
                    "{}: byte {s} changed line",
                    path.display()
                );
            }
        }

        for o in 0..out.check.len() as u32 {
            let s = out.map.to_source(o);
            assert!(
                s as usize <= src.len(),
                "{}: output byte {o} maps outside",
                path.display()
            );
            assert_eq!(
                line_of(&src, s as usize),
                line_of(&out.check, o as usize),
                "{}: output byte {o} maps to another line",
                path.display()
            );
        }
    }
}
