//! The Alloy keyword list, for a plain completion.

/// The Alloy keywords a plain completion offers. The child lists Luau's
/// own; these are the words the emit removes.
pub const ALLOY_KEYWORDS: &[&str] = &[
    "after",
    "as",
    "async",
    "attribute",
    "await",
    "band",
    "bnot",
    "bor",
    "bxor",
    "case",
    "class",
    "const",
    "declare",
    "default",
    "delete",
    "destroy",
    "each",
    "enum",
    "export",
    "extends",
    "for",
    "from",
    "impl",
    "import",
    "in",
    "interface",
    "is",
    "macro",
    "match",
    "namespace",
    "new",
    "on",
    "private",
    "public",
    "read",
    "remote",
    "requires",
    "satisfies",
    "shl",
    "shr",
    "struct",
    "trait",
    "try",
    "where",
    "with",
    "write",
];
