/*!
The position map's contract. For every copied byte, forward then back is
the identity. For every output byte, back lands inside the source. Every
generated byte maps to an anchor on the same line as its output.
*/

use std::fs;
use std::path::Path;

fn line_of(text: &str, offset: usize) -> usize {
    text[..offset.min(text.len())].matches('\n').count()
}

#[test]
fn forward_then_back_is_identity_on_copied_bytes() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/cases");

    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();

        if path.extension().and_then(|e| e.to_str()) != Some("aly") {
            continue;
        }

        let src = fs::read_to_string(&path).unwrap();
        let out = alloy::compile(&src).unwrap();

        for s in 0..=src.len() as u32 {
            if let Some(o) = out.map.to_output(s) {
                assert_eq!(out.map.to_source(o), s, "{}: byte {s}", path.display());
                assert_eq!(
                    line_of(&src, s as usize),
                    line_of(&out.ship, o as usize),
                    "{}: byte {s} changed line",
                    path.display()
                );
            }
        }

        for o in 0..out.ship.len() as u32 {
            let s = out.map.to_source(o);
            assert!(
                s as usize <= src.len(),
                "{}: output byte {o} maps outside",
                path.display()
            );
            assert_eq!(
                line_of(&src, s as usize),
                line_of(&out.ship, o as usize),
                "{}: output byte {o} maps to another line",
                path.display()
            );
        }
    }
}
